language: elixir
elixir:
  - 1.4.2
otp_release:
  - 18.2.1

services:
  - postgresql

env:
  global:
    - MIX_ENV=travis
    - MIX_HOME=$HOME/.kiex/mix

install:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

before_script:
  - kerl list installations
  - mix deps.compile
  - mix eqc.install --mini
  - mix compile
  - mix dialyzer --plt

script:
  - mix test

cache:
  directories:
  - $HOME/.kiex
  - _build
  - deps